#!/bin/sh

#wifi_ssid=$(nmcli device status | awk '$2 == "wifi" && $3 == "connected" {print $4}')

#echo $wifi_ssid


networks_info=$(nmcli device status | awk '$2 != "loopback" && $3 == "connected" {print $2, $4}')

if [ ! -z "$networks_info" ]
then
	output=""
	while read -r type connection
	do
		case $type in
		wifi)
			network_symbol=' '
			;;
		ethernet)
			network_symbol=' '
			;;
		*)
			network_symbol="$type: "
			;;
		esac
		#output+="$type: $connection, "
		output+="$network_symbol$connection | "
	done <<< "$networks_info"

	echo "${output% | }"
else
	#echo "No internet connection"
	echo "No internet connection"
	echo ""
	echo "#FF6644"
fi
