#!/bin/sh

HEADPHONES_SYMBOL=' '
SPEAKER_HIGH_SYMBOL=' '
SPEAKER_MED_SYMBOL=' '
SPEAKER_LOW_SYMBOL=' '
SPEAKER_MUTED_SYMBOL=' '
MICROPHONE_UNMUTED_SYMBOL=' '
MICROPHONE_MUTED_SYMBOL=' '


pactl_list_sinks=$(pactl list sinks)
pactl_list_source=$(pactl list sources)

active_port=$(echo "$pactl_list_sinks" | grep 'Active Port:' | awk '{print $3}')

output_volume=$(echo "$pactl_list_sinks" | grep 'Volume:' | head -n 1 | awk '{print $5}' | sed 's/[^0-9]*//g')
output_mute=$(echo "$pactl_list_sinks" | grep 'Mute:' | head -n 1 | awk '{print $2}')

microphone_volume=$(echo "$pactl_list_source" | grep -A 10 "Name: echoCancel_source" | grep "Volume:" | head -n 1 | awk '{print $5}' | sed 's/[^0-9]*//g')
microphone_mute=$(echo "$pactl_list_source" | grep -A 10 "Name: echoCancel_source" | grep "Mute:" | awk '{print $2}')


if [ $active_port = "analog-output-headphones" ]
then
	output_symbol=$HEADPHONES_SYMBOL
else
	if [ $output_mute = yes ]
	then
		output_symbol=$SPEAKER_MUTED_SYMBOL
	elif [ $output_volume -gt 50 ]
	then
		output_symbol=$SPEAKER_HIGH_SYMBOL
	elif [ $output_volume -gt 0 ]
	then
		output_symbol=$SPEAKER_MED_SYMBOL
	else
		output_symbol=$SPEAKER_LOW_SYMBOL
	fi
fi

if [ $microphone_mute = yes ]
then
	microphone_symbol=$MICROPHONE_MUTED_SYMBOL
else
	microphone_symbol=$MICROPHONE_UNMUTED_SYMBOL
fi


echo "$output_symbol${output_volume}% $microphone_symbol${microphone_volume}%"
