#!/bin/sh

SPEAKER_HIGH_SYMBOL=' '
SPEAKER_MED_SYMBOL=' '
SPEAKER_LOW_SYMBOL=' '
SPEAKER_MUTED_SYMBOL=' '

MICROPHONE_UNMUTED_SYMBOL=' '
MICROPHONE_MUTED_SYMBOL=' '

#mute=$(pactl list sinks | grep 'Mute:' | head -n 1 | awk '{print $2}')
#volume=$(pactl list sinks | grep 'Volume:' | head -n 1 | awk '{print $5}' | sed 's/[^0-9]*//g')

speaker_volume=$(pactl list sinks | grep 'Volume:' | head -n 1 | awk '{print $5}' | sed 's/[^0-9]*//g')
speaker_mute=$(pactl list sinks | grep 'Mute:' | head -n 1 | awk '{print $2}')

microphone_volume=$(pactl list sources | grep -A 10 "Name: echoCancel_source" | grep "Volume:" | head -n 1 | awk '{print $5}' | sed 's/[^0-9]*//g')
microphone_mute=$(pactl list sources | grep -A 10 "Name: echoCancel_source" | grep "Mute:" | awk '{print $2}')


#output="speaker: "
#[[ $speaker_mute = yes ]] && output=${output}muted || output=${output}${speaker_volume}%

if [ $speaker_mute = yes ]
then
	speaker_symbol=$SPEAKER_MUTED_SYMBOL
elif [ $speaker_volume -gt 50 ]
then
	speaker_symbol=$SPEAKER_HIGH_SYMBOL
elif [ $speaker_volume -gt 0 ]
then
	speaker_symbol=$SPEAKER_MED_SYMBOL
else
	speaker_symbol=$SPEAKER_LOW_SYMBOL
fi	
#output=${output}"${speaker_volume}%"


#output=${output}" | microphone: "
#[[ $microphone_mute = yes ]] && output=${output}muted || output=${output}${microphone_volume}%

if [ $microphone_mute = yes ]
then
	microphone_symbol=$MICROPHONE_MUTED_SYMBOL
else
	microphone_symbol=$MICROPHONE_UNMUTED_SYMBOL
fi

echo "$speaker_symbol${speaker_volume}% | $microphone_symbol${microphone_volume}%"
