#!/bin/sh

Shell=$(basename $SHELL)


zsh_prompt () {
	PROMPT=""
	PROMPT=$PROMPT"%B%F{black}[%f%F{blue}zsh%f%F{black}]%f%b"
	PROMPT=$PROMPT"%B%F{black}[%f%F{yellow}%~%f%F{black}]%f%b"
	PROMPT=$PROMPT" %B%F{white}%#%f%b: "
}

bash_prompt () {
	black_B="\[\e[1;30m\]"
	green_B="\[\e[1;32m\]"
	yellow_B="\[\e[1;33m\]"
	blue_B="\[\e[1;34m\]"
	purple_B="\[\e[1;35m\]"
	cyan_B="\[\e[1;36m\]"
	white_B="\[\e[1;37m\]"
	normal="\[\e[m\]"
	PS1=""
	PS1=$PS1"$black_B[${blue_B}bash$black_B]"
	PS1=$PS1"$black_B[$yellow_B\w$black_B]"
	PS1=$PS1" $white_B\$$white_B$normal: "
}

case $Shell in
	zsh) 
		zsh_prompt
		;;
	bash) 
		bash_prompt
		;;
	*) 
		PS1="> "
		;;
esac
